branch-defaults:
  default:
    environment: Udagram-api-host-env
environment-defaults:
  Udagram-api-host-env:
    branch: null
    repository: null
global:
  application_name: Udagram-api-host
  default_ec2_keyname: aws-eb
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
